"""empty message

Revision ID: 18100749fbe5
Revises: 847cd30c691e
Create Date: 2023-11-11 23:47:50.618557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18100749fbe5'
down_revision = '847cd30c691e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
