"""empty message

Revision ID: 213dadce741d
Revises: b77dc1191f38
Create Date: 2023-11-12 20:16:18.337509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213dadce741d'
down_revision = 'b77dc1191f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
